config/routes.rb
Rails.application.routes.draw do
  root 'static_people#home'
  
  get '/about', to: 'static_people#about'
 
  resources :people
end

# Notes from lecture
# Rails.application.routes.draw do
#   root 'static_pages#home'

#   get '/about', to: 'static_pages#about'

#   resources :pages
# end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/person.rb
class Person < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
    def index #shows all the people
        @people = Person.all
    end

    def new #show form to create new person
        @people = Person.new
    end

    def create #adds new person to database
        @people = Person.new(people_params)
        
           if @people.save
             redirect_to people_path
           else
             render :new
           end
    end

    def show #view one person
        @person = Person.find(params[:id])
    end

    def edit #form to edit a person who is already created
        @person = Person.find(params[:id])
    end

    def update #changes someone who is already in database
        @person = Person.find(params[:id])
          
            if @person.update(people_params)
              redirect_to people_path
            else
              render :edit
            end
     end

    def destroy
        @person = Person.find(params[:id]).destroy
        redirect_to person_path
    end
      

    private
    
       def people_params
         params.require(:person).permit(:nam, :age, :hair_color, :eye_color, :gender, :alive)
       end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/layouts/_navbar.html.erb
<%= link_to 'Home', people_path %>
<%= link_to 'Add New', new_person_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>People</title>
    <%= csrf_meta_tags %>

  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/people/edit.html.erb
<h1>Edit Person</h1>
<%= form_for @person do |f| %>

  <%= f.label :name %>
  <%= f.text_field :nam %>

  <%= f.label :age %>
  <%= f.text_field :age %>

  <%= f.label :hair_Color %>
  <%= f.text_field :hair_color %>

  <%= f.label :eye_color %>
  <%= f.text_field :eye_color %>

  <%= f.label :gender %>
  <%= f.text_field :gender %>

  <%= radio_button_tag(:alive, "alive") %>
  <%= label_tag(:alive, "Still Kickin") %>
  <%= radio_button_tag(:alive, "DEAD") %>
  <%= label_tag(:alive, "Stopped Kickin") %>
  
  <%= f.submit %>
  
<% end %>

app/views/people/index.html.erb
<h1>People List</h1>

<% @people.each do |person| %>
    <h2>Name: <%= person.nam %> Age: <%= person.age %></h2>

 <%=link_to 'More Info', person_path(person) %>  <%= link_to 'Edit', edit_person_path(person) %>  <%= link_to 'Delete', person, method: :delete %>
 
<% end %> 
    

app/views/people/new.html.erb
<h1> Add New Person </h1>

<%= form_for @people do |f| %>
  <%= f.label :name %>
  <%= f.text_field :nam %>

  <%= f.label :age %>
  <%= f.text_field :age %>

  <%= f.label :hair_Color %>
  <%= f.text_field :hair_color %>

  <%= f.label :eye_color %>
  <%= f.text_field :eye_color %>

  <%= f.label :gender %>
  <%= f.text_field :gender %>

  <%= radio_button_tag(:alive, "alive") %>
  <%= label_tag(:alive, "Still Kickin") %>
  <%= radio_button_tag(:alive, "DEAD") %>
  <%= label_tag(:alive, "Stopped Kickin") %>
  
  <%= f.submit %>
<% end %>

app/views/people/show.html.erb
    <h1> More Info </h1>
    <h2>Name: <%= @person.nam %></h2>
    <h2>Age: <%= @person.age %></h2>
    <h2>Hair Color: <%= @person.hair_color %></h2>
    <h2>Eye Color: <%= @person.eye_color %></h2>
    <h2>Gender: <%= @person.gender %></h2>
    <h2>This dude is still kickin': <%= @person.alive %></h2>

    <%= link_to 'Back', people_path %>  <%= link_to 'Edit', edit_person_path(@person) %>  <%= link_to 'Delete', @person, method: :delete %>